[[scales.major]]
name = 'Major'
mode = 'Ionian'
steps = [2, 2, 1, 2, 2, 2, 1]
intervals = [1, 2, 3, 4, 5, 6, 7]

[[scales.major-pentatonic]]
name = 'Major Pentatonic'
steps = [2, 2, 3, 2, 3]
intervals = [1, 2, 3, 5, 6]

[[scales.minor]]
name = 'Natural Minor'
mode = 'Aeolian'
steps = [2, 1, 2, 2, 1, 2, 2]
intervals = [1, 2, "♭3", 4, 5, "♭6", "♭7"]

[[scales.minor-pentatonic]]
name = 'Minor Pentatonic'
steps = [3, 2, 2, 3, 2]
intervals = [1, "♭3", 4, 5, "♭7"]
